# Generated by Django 4.1.6 on 2023-03-11 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_agegroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamname',
            name='age_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='football.agegroup'),
        ),
    ]
