# Generated by Django 4.1.6 on 2023-03-11 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0004_alter_teamname_age_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='age_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='football.agegroup'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='age_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='football.agegroup'),
        ),
        migrations.AlterField(
            model_name='teamname',
            name='age_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='football.agegroup'),
        ),
    ]
