# Generated by Django 4.1.6 on 2023-03-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0005_alter_fixture_age_group_alter_stat_age_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='age_group',
            field=models.CharField(choices=[('U7', 'U7'), ('U8', 'U8'), ('U9', 'U9'), ('U10', 'U10'), ('U11', 'U11'), ('U12', 'U12'), ('U13', 'U13'), ('U14', 'U14'), ('U15', 'U15'), ('U16', 'U16')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='stat',
            name='age_group',
            field=models.CharField(choices=[('U7', 'U7'), ('U8', 'U8'), ('U9', 'U9'), ('U10', 'U10'), ('U11', 'U11'), ('U12', 'U12'), ('U13', 'U13'), ('U14', 'U14'), ('U15', 'U15'), ('U16', 'U16')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='teamname',
            name='age_group',
            field=models.CharField(choices=[('U7', 'U7'), ('U8', 'U8'), ('U9', 'U9'), ('U10', 'U10'), ('U11', 'U11'), ('U12', 'U12'), ('U13', 'U13'), ('U14', 'U14'), ('U15', 'U15'), ('U16', 'U16')], max_length=3, null=True),
        ),
        migrations.DeleteModel(
            name='AgeGroup',
        ),
    ]
